apiVersion: v1
kind: Namespace
metadata:
  name: spring-example-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-example-deploy
  namespace: spring-example-ns
  labels:
    app: spring-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-example
  template:
    metadata:
      labels:
        app: spring-example
    spec:
      containers:
      - name: spring-example-container
        image: gazgeek/springboot-helloworld
        env:
            - name: TZ
              value: Asia/Ho_Chi_Minh
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
          requests:
            cpu: "1000m"
            memory: "2048Mi"
          limits:
            cpu: "1000m"
            memory: "2048Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-example-svc
  namespace: spring-example-ns
  labels:
    app: spring-example
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: spring-example
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-example-ingress
  namespace: spring-example-ns
spec:
  rules:
  - http:
      paths:
      - path: /spring-example
        pathType: Prefix
        backend:
          service:
            name: spring-example-svc
            port:
              number: 8080
