apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deploy
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak-container
        image: quay.io/keycloak/keycloak:19.0.0
        args: ["start-dev"]
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: KC_PROXY
          value: "edge"
        - name: KC_DB
          value: "mariadb"
        - name: KC_DB_URL
          value: "jdbc://mariadb://10.140.0.14:3306/keycloak-database"
        - name: KC_DB_USERNAME
          value: "resdii-admin"
        - name: KC_DB_PASSWORD
          value: "ResdiiQTHT2022"
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
        resources:
          requests:
            cpu: "800m"
            memory: "1024Mi"
          limits:
            cpu: "800m"
            memory: "1024Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-svc
  namespace: keycloak
spec:
  ports:
  - name: http-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: keycloak
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - host: "kc.resdii.com"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: keycloak-svc
            port:
              number: 8080
