apiVersion: v1
kind: Namespace
metadata:
  name: vars
---

### BACKEND ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vars-api-deploy
  namespace: vars
  labels:
    app: vars-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vars-api
  template:
    metadata:
      labels:
        app: vars-api
    spec:
      containers:
      - name: vars-api-container
        image: 34.81.200.132:5000/realtor-backend:1.0.0.r54
        env:
        - name: ENV_NOODEV_URL
          value: "http://app.noo-dev.com"
        - name: ENV_NOODEV_APP_ID
          value: "037d52eea5ae3445a3f6bea0d4ce45a9"
        - name: ENV_NOODEV_JAVA_KEY
          value: "YXoH5ik15Yi0XmdpgG5DdfnLnlT2jHzizEQMgAbz"
        - name: ENV_QR_CODE_PATH_PATTERN
          value: "https://vars.vn/qr/{{code}}"
        - name: ENV_KC_URL
          value: "http://keycloak-svc.keycloak:8080"
        - name: ENV_KC_ADMIN_REALM
          value: "master"
        - name: ENV_KC_APP_REALM
          value: "realtor"
        - name: ENV_KC_ADMIN_CLIENT
          value: "admin-cli"
        - name: ENV_KC_ADMIN_USERNAME
          value: "admin"
        - name: ENV_KC_ADMIN_PASSWORD
          value: "Z@HG$$3_BQXKVzV4j"
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "1024Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
      hostAliases:
        - ip: "34.135.67.125"
          hostnames:
            - "app.noo-dev.com"
---
apiVersion: v1
kind: Service
metadata:
  name: vars-api-svc
  namespace: vars
spec:
  ports:
  - name: http-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: vars-api
---
apiVersion: v1
kind: Secret
metadata:
  name: vars-api-tls
  namespace: vars
type: kubernetes.io/tls
data:
  server.crt: |
	-----BEGIN CERTIFICATE----- 
	MIIGNzCCBR+gAwIBAgIRAKwXk0I/POKobM7E/PPgNeUwDQYJKoZIhvcNAQELBQAw 
	gY8xCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO 
	BgNVBAcTB1NhbGZvcmQxGDAWBgNVBAoTD1NlY3RpZ28gTGltaXRlZDE3MDUGA1UE 
	AxMuU2VjdGlnbyBSU0EgRG9tYWluIFZhbGlkYXRpb24gU2VjdXJlIFNlcnZlciBD 
	QTAeFw0yMjA2MDIwMDAwMDBaFw0yMzA2MDIyMzU5NTlaMBoxGDAWBgNVBAMTD3d3 
	dy5hcGkudmFycy52bjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK8p 
	6optWIrSAT48eVegl6Sve2zftUcQoW0p9fBELl4W6gizM+pUAX9vOlLBd4I9a/CV 
	TTuydYQxghnlCwqfwhuGDdGLHzSzfePyZZBas0jFRvOEKkj997eZVT625e9ruDis 
	cVi63dwknYPis0kOJLbMleaONO3jyO0Mq/JIp8ZOyZnEkGOe/y4Fd7nbbNc97VSq 
	bH9a/61dMgEMNzQasL9pgfOXGCiHKZn7bCwpeMfmB0BhiWEcRd4zoZZSr/SBsZfX 
	xF+zyqODPF0q3S0Omge92cPiL+NmJ90MkM2EGnLkjQT4SqKu6orkmjRVXxYVzR9X 
	L5oUMz63affkoF2vNwsCAwEAAaOCAwAwggL8MB8GA1UdIwQYMBaAFI2MXsRUrYrh 
	d+mb+ZsF4bgBjWHhMB0GA1UdDgQWBBSAPv8OGZ+CKKymRm6TorFntLoCQTAOBgNV 
	HQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYI 
	KwYBBQUHAwIwSQYDVR0gBEIwQDA0BgsrBgEEAbIxAQICBzAlMCMGCCsGAQUFBwIB 
	FhdodHRwczovL3NlY3RpZ28uY29tL0NQUzAIBgZngQwBAgEwgYQGCCsGAQUFBwEB 
	BHgwdjBPBggrBgEFBQcwAoZDaHR0cDovL2NydC5zZWN0aWdvLmNvbS9TZWN0aWdv 
	UlNBRG9tYWluVmFsaWRhdGlvblNlY3VyZVNlcnZlckNBLmNydDAjBggrBgEFBQcw 
	AYYXaHR0cDovL29jc3Auc2VjdGlnby5jb20wJwYDVR0RBCAwHoIPd3d3LmFwaS52 
	YXJzLnZuggthcGkudmFycy52bjCCAYAGCisGAQQB1nkCBAIEggFwBIIBbAFqAHcA 
	rfe++nz/EMiLnT2cHj4YarRnKV3PsQwkyoWGNOvcgooAAAGBJWSJZAAABAMASDBG 
	AiEAmdRr1MSQ9U6jsX7yZ4G15d2y3PLfeIFwax5uy4YXseUCIQCqTd/ltWxrS+gh 
	cgHCwWGolLm7Fxy80RTLnBayz9Vm3gB3AHoyjFTYty22IOo44FIe6YQWcDIThU07 
	0ivBOlejUutSAAABgSVkiZ0AAAQDAEgwRgIhAOyBgzWoL2AbB/pRWVkZj5mqE2N1 
	HAWOei5ck3/3EhKiAiEApWIXdyI5szWnUncL+Bno+cp9ySYSg+MwhkyIBNI6aLkA 
	dgDoPtDaPvUGNTLnVyi8iWvJA9PL0RFr7Otp4Xd9bQa9bgAAAYElZIlEAAAEAwBH 
	MEUCIQDUmgGKZDYmhbMr8UfozLLcVFUYP7jeB5+CIAA1L4ZmJQIgANH6Z2z0nKYX 
	2JErrL7y6Maj4w2v8Uek0te0fJC+stswDQYJKoZIhvcNAQELBQADggEBAF3M4DTT 
	9TNPe+Ga68+JK24lLY1wfW97QYDYYKQcZTvNx+N03pra1HUafiiSOzO5nFz+q9S3 
	CgLQdnTJu5LeBRU7Z/JoQW9RFpFSdQMtdVSjsbH+wrUGhjQeJ/S7q9yqFmgIufMc 
	dBe+NZoLc+AGKBVJ+zDckY6tSsFQfAyPAUOmEekFDFasY+NnN7wIbjIohX7l7V8W 
	/5IuqoIOTIxgQzN3+VcS7cFzdf1nHDVjERhqqk49sZFlZEbRuK2+IEqwUF09VYib 
	JQ/8T3tA4bvqQ8eMiQ58ygrgLnZyvqkb6qyQy5gCIY2zeXXLQ+pC375rYMf9EmJ+ 
	MM73GiPpyiqRZ9s= 
	-----END CERTIFICATE----- 
	-----BEGIN CERTIFICATE----- 
	MIIGEzCCA/ugAwIBAgIQfVtRJrR2uhHbdBYLvFMNpzANBgkqhkiG9w0BAQwFADCB 
	iDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCk5ldyBKZXJzZXkxFDASBgNVBAcTC0pl 
	cnNleSBDaXR5MR4wHAYDVQQKExVUaGUgVVNFUlRSVVNUIE5ldHdvcmsxLjAsBgNV 
	BAMTJVVTRVJUcnVzdCBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTgx 
	MTAyMDAwMDAwWhcNMzAxMjMxMjM1OTU5WjCBjzELMAkGA1UEBhMCR0IxGzAZBgNV 
	BAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEYMBYGA1UE 
	ChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQDEy5TZWN0aWdvIFJTQSBEb21haW4g 
	VmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENBMIIBIjANBgkqhkiG9w0BAQEFAAOC 
	AQ8AMIIBCgKCAQEA1nMz1tc8INAA0hdFuNY+B6I/x0HuMjDJsGz99J/LEpgPLT+N 
	TQEMgg8Xf2Iu6bhIefsWg06t1zIlk7cHv7lQP6lMw0Aq6Tn/2YHKHxYyQdqAJrkj 
	eocgHuP/IJo8lURvh3UGkEC0MpMWCRAIIz7S3YcPb11RFGoKacVPAXJpz9OTTG0E 
	oKMbgn6xmrntxZ7FN3ifmgg0+1YuWMQJDgZkW7w33PGfKGioVrCSo1yfu4iYCBsk 
	Haswha6vsC6eep3BwEIc4gLw6uBK0u+QDrTBQBbwb4VCSmT3pDCg/r8uoydajotY 
	uK3DGReEY+1vVv2Dy2A0xHS+5p3b4eTlygxfFQIDAQABo4IBbjCCAWowHwYDVR0j 
	BBgwFoAUU3m/WqorSs9UgOHYm8Cd8rIDZsswHQYDVR0OBBYEFI2MXsRUrYrhd+mb 
	+ZsF4bgBjWHhMA4GA1UdDwEB/wQEAwIBhjASBgNVHRMBAf8ECDAGAQH/AgEAMB0G 
	A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAbBgNVHSAEFDASMAYGBFUdIAAw 
	CAYGZ4EMAQIBMFAGA1UdHwRJMEcwRaBDoEGGP2h0dHA6Ly9jcmwudXNlcnRydXN0 
	LmNvbS9VU0VSVHJ1c3RSU0FDZXJ0aWZpY2F0aW9uQXV0aG9yaXR5LmNybDB2Bggr 
	BgEFBQcBAQRqMGgwPwYIKwYBBQUHMAKGM2h0dHA6Ly9jcnQudXNlcnRydXN0LmNv 
	bS9VU0VSVHJ1c3RSU0FBZGRUcnVzdENBLmNydDAlBggrBgEFBQcwAYYZaHR0cDov 
	L29jc3AudXNlcnRydXN0LmNvbTANBgkqhkiG9w0BAQwFAAOCAgEAMr9hvQ5Iw0/H 
	ukdN+Jx4GQHcEx2Ab/zDcLRSmjEzmldS+zGea6TvVKqJjUAXaPgREHzSyrHxVYbH 
	7rM2kYb2OVG/Rr8PoLq0935JxCo2F57kaDl6r5ROVm+yezu/Coa9zcV3HAO4OLGi 
	H19+24rcRki2aArPsrW04jTkZ6k4Zgle0rj8nSg6F0AnwnJOKf0hPHzPE/uWLMUx 
	RP0T7dWbqWlod3zu4f+k+TY4CFM5ooQ0nBnzvg6s1SQ36yOoeNDT5++SR2RiOSLv 
	xvcRviKFxmZEJCaOEDKNyJOuB56DPi/Z+fVGjmO+wea03KbNIaiGCpXZLoUmGv38
	sbZXQm2V0TP2ORQGgkE49Y9Y3IBbpNV9lXj9p5v//cWoaasm56ekBYdbqbe4oyAL 
	l6lFhd2zi+WJN44pDfwGF/Y4QA5C5BIG+3vzxhFoYt/jmPQT2BVPi7Fp2RBgvGQq 
	6jG35LWjOhSbJuMLe/0CjraZwTiXWTb2qHSihrZe68Zk6s+go/lunrotEbaGmAhY 
	LcmsJWTyXnW0OMGuf1pGg+pRyrbxmRE1a6Vqe8YAsOf4vmSyrcjC8azjUeqkk+B5 
	yOGBQMkKW+ESPMFgKuOXwIlCypTPRpgSabuY0MLTDXJLR27lk8QyKGOHQ+SwMj4K 
	00u/I5sUKUErmgQfky3xxzlIPK1aEn8= 
	-----END CERTIFICATE----- 
	-----BEGIN CERTIFICATE----- 
	MIIFgTCCBGmgAwIBAgIQOXJEOvkit1HX02wQ3TE1lTANBgkqhkiG9w0BAQwFADB7 
	MQswCQYDVQQGEwJHQjEbMBkGA1UECAwSR3JlYXRlciBNYW5jaGVzdGVyMRAwDgYD 
	VQQHDAdTYWxmb3JkMRowGAYDVQQKDBFDb21vZG8gQ0EgTGltaXRlZDEhMB8GA1UE 
	AwwYQUFBIENlcnRpZmljYXRlIFNlcnZpY2VzMB4XDTE5MDMxMjAwMDAwMFoXDTI4 
	MTIzMTIzNTk1OVowgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpOZXcgSmVyc2V5 
	MRQwEgYDVQQHEwtKZXJzZXkgQ2l0eTEeMBwGA1UEChMVVGhlIFVTRVJUUlVTVCBO 
	ZXR3b3JrMS4wLAYDVQQDEyVVU0VSVHJ1c3QgUlNBIENlcnRpZmljYXRpb24gQXV0 
	aG9yaXR5MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAgBJlFzYOw9sI 
	s9CsVw127c0n00ytUINh4qogTQktZAnczomfzD2p7PbPwdzx07HWezcoEStH2jnG 
	vDoZtF+mvX2do2NCtnbyqTsrkfjib9DsFiCQCT7i6HTJGLSR1GJk23+jBvGIGGqQ 
	Ijy8/hPwhxR79uQfjtTkUcYRZ0YIUcuGFFQ/vDP+fmyc/xadGL1RjjWmp2bIcmfb 
	IWax1Jt4A8BQOujM8Ny8nkz+rwWWNR9XWrf/zvk9tyy29lTdyOcSOk2uTIq3XJq0 
	tyA9yn8iNK5+O2hmAUTnAU5GU5szYPeUvlM3kHND8zLDU+/bqv50TmnHa4xgk97E 
	xwzf4TKuzJM7UXiVZ4vuPVb+DNBpDxsP8yUmazNt925H+nND5X4OpWaxKXwyhGNV 
	icQNwZNUMBkTrNN9N6frXTpsNVzbQdcS2qlJC9/YgIoJk2KOtWbPJYjNhLixP6Q5 
	D9kCnusSTJV882sFqV4Wg8y4Z+LoE53MW4LTTLPtW//e5XOsIzstAL81VXQJSdhJ 
	WBp/kjbmUZIO8yZ9HE0XvMnsQybQv0FfQKlERPSZ51eHnlAfV1SoPv10Yy+xUGUJ 
	5lhCLkMaTLTwJUdZ+gQek9QmRkpQgbLevni3/GcV4clXhB4PY9bpYrrWX1Uu6lzG 
	KAgEJTm4Diup8kyXHAc/DVL17e8vgg8CAwEAAaOB8jCB7zAfBgNVHSMEGDAWgBSg 
	EQojPpbxB+zirynvgqV/0DCktDAdBgNVHQ4EFgQUU3m/WqorSs9UgOHYm8Cd8rID 
	ZsswDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wEQYDVR0gBAowCDAG 
	BgRVHSAAMEMGA1UdHwQ8MDowOKA2oDSGMmh0dHA6Ly9jcmwuY29tb2RvY2EuY29t 
	L0FBQUNlcnRpZmljYXRlU2VydmljZXMuY3JsMDQGCCsGAQUFBwEBBCgwJjAkBggr 
	BgEFBQcwAYYYaHR0cDovL29jc3AuY29tb2RvY2EuY29tMA0GCSqGSIb3DQEBDAUA 
	A4IBAQAYh1HcdCE9nIrgJ7cz0C7M7PDmy14R3iJvm3WOnnL+5Nb+qh+cli3vA0p+ 
	rvSNb3I8QzvAP+u431yqqcau8vzY7qN7Q/aGNnwU4M309z/+3ri0ivCRlv79Q2R+ 
	/czSAaF9ffgZGclCKxO/WIu6pKJmBHaIkU4MiRTOok3JMrO66BQavHHxW/BBC5gA 
	CiIDEOUMsfnNkjcZ7Tvx5Dq2+UUTJnWvu6rvP3t3O9LEApE9GQDTF1w52z97GA1F 
	zZOFli9d31kWTz9RvdVFGD/tSo7oBmF0Ixa1DVBzJ0RHfxBdiSprhTEUxOipakyA 
	vGp4z7h/jnZymQyd/teRCBaho1+V 
	-----END CERTIFICATE----- 
	-----BEGIN CERTIFICATE----- 
	MIIEMjCCAxqgAwIBAgIBATANBgkqhkiG9w0BAQUFADB7MQswCQYDVQQGEwJHQjEb 
	MBkGA1UECAwSR3JlYXRlciBNYW5jaGVzdGVyMRAwDgYDVQQHDAdTYWxmb3JkMRow 
	GAYDVQQKDBFDb21vZG8gQ0EgTGltaXRlZDEhMB8GA1UEAwwYQUFBIENlcnRpZmlj 
	YXRlIFNlcnZpY2VzMB4XDTA0MDEwMTAwMDAwMFoXDTI4MTIzMTIzNTk1OVowezEL 
	MAkGA1UEBhMCR0IxGzAZBgNVBAgMEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UE 
	BwwHU2FsZm9yZDEaMBgGA1UECgwRQ29tb2RvIENBIExpbWl0ZWQxITAfBgNVBAMM 
	GEFBQSBDZXJ0aWZpY2F0ZSBTZXJ2aWNlczCCASIwDQYJKoZIhvcNAQEBBQADggEP 
	ADCCAQoCggEBAL5AnfRu4ep2hxxNRUSOvkbIgwadwSr+GB+O5AL686tdUIoWMQua 
	BtDFcCLNSS1UY8y2bmhGC1Pqy0wkwLxyTurxFa70VJoSCsN6sjNg4tqJVfMiWPPe 
	3M/vg4aijJRPn2jymJBGhCfHdr/jzDUsi14HZGWCwEiwqJH5YZ92IFCokcdmtet4 
	YgNW8IoaE+oxox6gmf049vYnMlhvB/VruPsUK6+3qszWY19zjNoFmag4qMsXeDZR 
	rOme9Hg6jc8P2ULimAyrL58OAd7vn5lJ8S3frHRNG5i1R8XlKdH5kBjHYpy+g8cm 
	ez6KJcfA3Z3mNWgQIJ2P2N7Sw4ScDV7oL8kCAwEAAaOBwDCBvTAdBgNVHQ4EFgQU 
	oBEKIz6W8Qfs4q8p74Klf9AwpLQwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQF 
	MAMBAf8wewYDVR0fBHQwcjA4oDagNIYyaHR0cDovL2NybC5jb21vZG9jYS5jb20v 
	QUFBQ2VydGlmaWNhdGVTZXJ2aWNlcy5jcmwwNqA0oDKGMGh0dHA6Ly9jcmwuY29t 
	b2RvLm5ldC9BQUFDZXJ0aWZpY2F0ZVNlcnZpY2VzLmNybDANBgkqhkiG9w0BAQUF 
	AAOCAQEACFb8AvCb6P+k+tZ7xkSAzk/ExfYAWMymtrwUSWgEdujm7l3sAg9g1o1Q 
	GE8mTgHj5rCl7r+8dFRBv/38ErjHT1r0iWAFf2C3BUrz9vHCv8S5dIa2LX1rzNLz 
	Rt0vxuBqw8M0Ayx9lt1awg6nCpnBBYurDC/zXDrPbDdVCYfeU0BsWO/8tqtlbgT2 
	G9w84FoVxp7Z8VlIMCFlA2zs6SFz7JsDoeA3raAVGI/6ugLOpyypEBMs1OUIJqsi 
	l2D4kF501KKaU73yqWjgom7C12yxow+ev+to51byrvLjKzg6CYG1a4XXvi3tPxq3 
	smPi9WIsgtRqAEFQ8TmDn5XpNpaYbg== 
	-----END CERTIFICATE-----
  server.key: |
	-----BEGIN PRIVATE KEY----- 
	MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCvKeqKbViK0gE+ 
	PHlXoJekr3ts37VHEKFtKfXwRC5eFuoIszPqVAF/bzpSwXeCPWvwlU07snWEMYIZ 
	5QsKn8Ibhg3Rix80s33j8mWQWrNIxUbzhCpI/fe3mVU+tuXva7g4rHFYut3cJJ2D 
	4rNJDiS2zJXmjjTt48jtDKvySKfGTsmZxJBjnv8uBXe522zXPe1Uqmx/Wv+tXTIB 
	DDc0GrC/aYHzlxgohymZ+2wsKXjH5gdAYYlhHEXeM6GWUq/0gbGX18Rfs8qjgzxd 
	Kt0tDpoHvdnD4i/jZifdDJDNhBpy5I0E+EqiruqK5Jo0VV8WFc0fVy+aFDM+t2n3 
	5KBdrzcLAgMBAAECggEBAJ/+84MZueSjSgtlBZkq0RjWSTD7bgPJhwnFaCXcwVWk 
	LIVh2qvRq8SQ/n8UxGqsW+nXFkLPEVR8PFAWzG0Z3B1z5y9dmlVzFiyd/nNKxbRU 
	rihEsrMVd622Wwz71y9H/2+U47uehIRO1anf6s9yIcrvOITtpB8fDyqnhm+6ObWC 
	QsJnG5hFNLVyATVrf/V4VelLh7fy1OjymFnAvNB87zQq3OP2AJn4oLMUpUTxiioj 
	qsK8oYxjkbCVT85iOefwhCqMCi7OoVeVNvKSsWUSySoyuqL4RXAQZGw3m2yyPjvp 
	zy4RS54A4NZyA932/pVJPOC80rwMLULl5JmMOwShJnECgYEA2zLNxTWosVtExwGQ 
	Uwid+nOonlvMhHaybRq0WjtTb8mK1dJUZC+5s23glRKV8lvlZ4Htbf1sfG2D+wFA 
	9bwxBQX4NaRWt/JAFW1d9OjNee/7920Dgv0gtYAJdjhoksy2yfgTLCARYSeJR/Cm 
	tCsmc16+c6YHuDHfmSrpA3G7aB0CgYEAzJJ9qE/Ey4Yj78Q9J0y0EWxdEex23N9p 
	UxVc7JNmkDdnFGnHFYKuKc3CavLr+bwgsaTHr4x6zylXWztL+N66qZjtugya5u0A 
	rzZw9D3oRGVm6Sp50Q02vfXywrUj1LPWdOtQWXx2saIFXMAdxNLVVxeq4JuW9O84 
	EsONzGvhA0cCgYBdyLbRkcvDVlFu8/RUEnPFHIcgehZe9ooQtERF9uwUAB8urPb+ 
	hozlgDV+kp0lPLxCNQzo6mzoL9MwKbEpcoNmqs8v5EhWG4ffoxN4HcMMUOl1S2cd 
	PEAqZ8Wkly3m4T+z2jgZwP6umsPZy9UHcQ7afcbupDLZVD1ew0U+/AI64QKBgQDJ 
	G33yd7DET7OGYwmnV81xj3ETTL4xNmRJbCf03pcmUYDBXZd8ewKSUBe/od3/nUUa 
	vh4cYuLcQw0AwBNYrkUcsx2JGBkzyWwx0zhJs45hprn7oGku7WmSZ3XmmcKGuOCs 
	AiT0Q9o/mELjQm5Bbu6R9s9ijTJiycT7FUmR27/RwwKBgDx+fbX2YLGkab69bIX1 
	+t20VaZI08Ias2Sdu/tSprYChYvPExAeckqReVcw4pPg082mILvSb3Uk0A3lyqlZ 
	8I8MhcXuJcpITQax3PvtWsJiuFV2ts/MuWXdYkHUr1qYmqu35zXTnQB9MVxe9HdA 
	bBQwvdSdccJ3Ct5NVxbT+l7M 
	-----END PRIVATE KEY-----
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vars-api-ingress
  namespace: vars
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  tls:
  - hosts:
    - api.vars.vn
    secretName: vars-api-tls
  rules:
  - host: "api.vars.vn"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: vars-api-svc
            port:
              number: 8080
---

### FRONTEND ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vars-frontend-deploy
  namespace: vars
  labels:
    app: vars-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vars-frontend
  template:
    metadata:
      labels:
        app: vars-frontend
    spec:
      containers:
      - name: vars-frontend-container
        image: 34.81.200.132:5000/realtor-frontend:1.0.0.r33
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            cpu: "500m"
            memory: "1024Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: vars-frontend-svc
  namespace: vars
spec:
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: vars-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vars-frontend-ingress
  namespace: vars
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - host: "vars.vn"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: vars-frontend-svc
            port:
              number: 80
