### NAMESPACE ###
apiVersion: v1
kind: Namespace
metadata:
  name: noodev-system
---

### LANDING PAGE ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noodev-landing-page-deploy
  namespace: noodev-system
  labels:
    app: noodev-landing-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noodev-landing-page
  template:
    metadata:
      labels:
        app: noodev-landing-page
    spec:
      containers:
      - name: noodev-landing-page-container
        image: 10.140.0.14:5000/noodev-landing-page:1.0.0.stable
        securityContext:
          runAsUser: 1000
        env:
            - name: TZ
              value: Asia/Ho_Chi_Minh
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "1024Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: noodev-landing-page-svc
  namespace: noodev-system
  labels:
    app: noodev-landing-page
spec:
  ports:
  - name: http-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: noodev-landing-page
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: noodev-landing-page-ingress
  namespace: noodev-system
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "noo-dev.com"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: noodev-landing-page-svc
            port:
              number: 8080
---

### GUIDE DOCS ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noodev-guide-docs-deploy
  namespace: noodev-system
  labels:
    app: noodev-guide-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noodev-guide-docs
  template:
    metadata:
      labels:
        app: noodev-guide-docs
    spec:    
      containers:
      - name: noodev-guide-docs-container
        image: 10.140.0.14:5000/noodev-guide-docs:1.0.0.stable
        env:
            - name: TZ
              value: Asia/Ho_Chi_Minh
        ports:
        - containerPort: 443
        resources:
          requests:
            cpu: "500m"
            memory: "1024Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: noodev-guide-docs-svc
  namespace: noodev-system
  labels:
    app: noodev-guide-docs
spec:
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: noodev-guide-docs
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: noodev-guide-docs-ingress
  namespace: noodev-system
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "docs.noo-dev.com"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: noodev-guide-docs-svc
            port:
              number: 80

---
### CMS ###
apiVersion: v1
kind: ConfigMap
metadata:
  name: noodev-core-cms-backend-cfm
  namespace: noodev-system
data:
  noodev-core-cms-backend-config.json : |
    {
      "appId": "3395f1ca946543079288aa0228e5bd8d",
      "appName": "NOODEV BASS SERVER",
      "mountPath": "/noodev-cms",
      "publicServerURL": "http://localhost:1337/noodev-cms",
      "masterKey": "AgKdD2HH5gc1MPDoN9cF8dzle27bBHm9em0TcqoI",
      "javascriptKey": "xyAp51H18TQ6GhOj7Pg2KJCJxPNPFeCgt4HxqKL2",
      "javaKey": "NmfFOPBpqTL061EMGe7xgqDphzoB9tNA6X8g8i80",
      "restAPIKey": "QxIcoQmCLpnyp9fM9A719XOzFHeeJcgGkG7lOCFy",
      "clientKey": "qyH2x9XxCEg8zztMlnEJNiLHIhaInYKnDKKq39Qz",
      "databaseURI": "mongodb://app:ResdiiATApp2022@database-server-1:27017,database-server-2:27017,database-server-3:27017/noodev-system-database?replicaSet=mongo_rep",
      "verifyUserEmails": false,
      "useValidateKey": true,
      "preventLoginWithUnverifiedEmail": true,
      "fileUpload": {
        "enableForAnonymousUser": false,
        "enableForPublic": false,
        "enableForAuthenticatedUser": false
      },
      "allowClientClassCreation": true,
      "customPages": {},
      "passwordPolicy": {
        "validatorPattern": null,
        "doNotAllowUsername": false,
        "maxPasswordAge": null,
        "maxPasswordHistory": null,
        "resetTokenValidityDuration": 21178800
      },
      "sessionLength": 86400,
      "databaseOptions": {
        "serverSelectionTimeoutMS": 60000
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noodev-core-cms-backend-deploy
  namespace: noodev-system
spec:
  selector:
    matchLabels:
      app: noodev-core-cms-backend
  template:
    metadata:
      labels:
        app: noodev-core-cms-backend
    spec:
      volumes:
      - name: noodev-core-cms-backend-config
        configMap:
           name: noodev-core-cms-backend-cfm
      containers:
      - name: noodev-core-cms-backend-container
        image: 10.140.0.14:5000/noodev-cms-backend:1.0.0.stable
        env:
            - name: TZ
              value: Asia/Ho_Chi_Minh
        command: ["npm","start",--,]
        args: ["/etc/config/noodev-core-cms-backend-config.json"]
        ports:
        - containerPort: 1337
        readinessProbe:
          httpGet:
            path: /noodev-cms/health
            port: 1337
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 3
          failureThreshold: 100
        volumeMounts:
          - name: noodev-core-cms-backend-config
            mountPath: "/etc/config"
        resources:
          requests:
            cpu: "500m"
            memory: "1024Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
      hostAliases:
        - ip: "10.128.0.11"
          hostnames:
            - "database-server-1"
        - ip: "10.128.0.10"
          hostnames:
            - "database-server-2"
        - ip: "10.128.0.12"
          hostnames:
            - "database-server-3"
---
apiVersion: v1
kind: Service
metadata:
  name: noodev-core-cms-backend-svc
  namespace: noodev-system
spec:
  ports:
  - name: http-port
    protocol: TCP
    port: 1337
    targetPort: 1337
  selector:
    app: noodev-core-cms-backend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: noodev-core-cms-backend-ingress
  namespace: noodev-system
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "cms-api.noo-dev.com"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: noodev-core-cms-backend-svc
            port:
              number: 1337
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: noodev-system
  name: noodev-core-cms-webapp-cfm
data:
  noodev-core-cms-webapp-config.json : |
    {
      "apps": [
        {
          "serverURL": "http://cms-api.noo-dev.com/noodev-cms",
          "appId": "3395f1ca946543079288aa0228e5bd8d",
          "masterKey": "AgKdD2HH5gc1MPDoN9cF8dzle27bBHm9em0TcqoI",
          "appName": "NOODEV BASS SERVER",
          "appNameForURL": "3395f1ca946543079288aa0228e5bd8d",
          "iconName": "",
          "primaryBackgroundColor": "",
          "secondaryBackgroundColor": "",
          "excludeClasses": [],
          "serverInfo": {
            "features": {
              "globalConfig": {
                "create": true,
                "read": true,
                "update": true,
                "delete": true
              },
              "hooks": false,
              "cloudCode": false,
              "logs": {
                "level": true,
                "size": true,
                "order": true,
                "until": true,
                "from": true
              },
              "push": false,
              "schemas": {
                "addField": true,
                "removeField": true,
                "addClass": true,
                "removeClass": true,
                "clearAllDataFromClass": true,
                "import": true,
                "exportClass": true,
                "editClassLevelPermissions": true,
                "editPointerPermissions": true
              }
            }
          }
        }
      ],
      "iconsFolder": "icons",
      "users": [
        {
          "user": "noodev_admin@resdii.com",
          "pass": "123456@noodev",
          "apps": [
            {
              "appId": "3395f1ca946543079288aa0228e5bd8d"
            }
          ]
        }
      ]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noodev-core-cms-webapp-deploy
  namespace: noodev-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noodev-core-cms-webapp
  template:
    metadata:
      labels:
        app: noodev-core-cms-webapp
    spec:
      volumes:
      - name: noodev-core-cms-webapp-config
        configMap:
           name: noodev-core-cms-webapp-cfm      
      containers:
      - name: noodev-core-cms-webapp-container
        image: 10.140.0.14:5000/noodev-cms-webapp:1.0.0.stable
        env:
            - name: TZ
              value: Asia/Ho_Chi_Minh
        command: ["npm","start",--,--config]
        args: [/etc/config/noodev-core-cms-webapp-config.json,--allowInsecureHTTP]
        ports:
        - containerPort: 4040
        volumeMounts:
          - name: noodev-core-cms-webapp-config
            mountPath: "/etc/config"
        resources:
          requests:
            cpu: "500m"
            memory: "1024Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: noodev-core-cms-webapp-svc
  namespace: noodev-system
spec:
  ports:
  - name: http-port
    protocol: TCP
    port: 4040
    targetPort: 4040
  selector:
    app: noodev-core-cms-webapp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: noodev-core-cms-webapp-ingress
  namespace: noodev-system
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "cms.noo-dev.com"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: noodev-core-cms-webapp-svc
            port:
              number: 4040
---

### BACKEND ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noodev-backend-deploy
  namespace: noodev-system
spec:
  selector:
    matchLabels:
      app: noodev-backend
  template:
    metadata:
      labels:
        app: noodev-backend
    spec:
      containers:
      - name: noodev-backend-container
        image: 10.60.156.72/vbcs/vbcs-core-api:1.0.0_u478.stable
        env:
            - name: TZ
              value: Asia/Ho_Chi_Minh
            - name: BAAS_SERVER_URL
              value: http://noodev-core-cms-backend-svc:1337/noodev-cms
            - name: IS_TESTING_ENV
              value: "0"
            - name: BAAS_APP_ID
              value: 3395f1ca946543079288aa0228e5bd8d
            - name: BAAS_JAVA_KEY
              value: NmfFOPBpqTL061EMGe7xgqDphzoB9tNA6X8g8i80
            - name: BAAS_MASTER_KEY
              value: AgKdD2HH5gc1MPDoN9cF8dzle27bBHm9em0TcqoI
            - name: KEY_K8S_CONFIG_BASE64
              value: YXBpVmVyc2lvbjogdjEKa2luZDogQ29uZmlnCmNsdXN0ZXJzOgotIGNsdXN0ZXI6CiAgICBhcGktdmVyc2lvbjogdjEKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VOM2FrTkRRV0Z4WjBGM1NVSkJaMGxDUVVSQlRrSm5hM0ZvYTJsSE9YY3dRa0ZSYzBaQlJFRlRUVkpCZDBSbldVUldVVkZFUlhka2NtUlhTbXdLVEZkT2FFMUNORmhFVkVsNFRVUnJlVTVxUlRKT1JGbDRUVVp2V0VSVVRYaE5SR3Q1VGtSRk1rNUVXWGhOUm05M1JXcEZVVTFCTkVkQk1WVkZRWGhOU0FwaE0xWnBXbE14YWxsVVEwTkJVMGwzUkZGWlNrdHZXa2xvZG1OT1FWRkZRa0pSUVVSblowVlFRVVJEUTBGUmIwTm5aMFZDUVU5M1duQTBNbXhuYUUwNUNsZG1ibGQ0UW5CVFZFeGhRMVpTVVdkMFMwdEpRMWxxVUdST1NXaFhWVzB6VnpGWllVOTVLM1pFWVVvMloxSlZZbWMxTjJocE4xZGhkV0ZVYlhONFVXUUtSbFZQWW14S1QwbGxaV1J4WlhOd1RHaEtWRU4wT1U5V2FXZExOazExVDBFeFIzVkZjVkV6V25Sd1J6TklRbVYyYUc1c1ZXaDVOamhPUVcxdWNVUjJTd3AyU0dkcVFsWm5jRTF6WVhFemNIUTVjR0ZTT1RkYVZFcGFNbFpFV1dReFFWRk5jeTh4ZUd3NVNYQjNlR2RpTVhGeGEwRlRZa1l3YXpoaFpGY3ZWa0owQ25jMU0wVnhOM0ppY210YVl5dFJZaTlHWTBsYVpHMUliM1ZTYUd0U2NHNVlZMnd5V214ck9WZzNjSFUzWm0xSFZXOHhVRzltTlhwR1RsaHdlV1ZSZHpFS1JsRkRRWEpLTkhkelNXdFVibGM0WVhoNk56WjZOMUl6YzBGblMxSlhRa1phVDNSdVVWUnhTRWRHUm01NFNGVnZiR2x2YTFreFRrWnpXRWRFTVdWa1NBcHdaMUk0UkdNdlpVRlhhME5CZDBWQlFXRk5hazFEUlhkRVoxbEVWbEl3VUVGUlNDOUNRVkZFUVdkTGEwMUJPRWRCTVZWa1JYZEZRaTkzVVVaTlFVMUNDa0ZtT0hkRVVWbEtTMjlhU1doMlkwNUJVVVZNUWxGQlJHZG5SVUpCUVhsT0swWXZia2xWWWxZeE9FeHVUMUp1SzBsYVJGaElTbUZOVjI5TE5sTjZRVmdLUWpFMWRsZ3JObEZqZFZGRk9XaFdTMWQ1UlU5a1pscHZhVXRRZDBKeE1ESjZRa1UwZFdFcldGRlhVbEpNZGsxMWVEWlNUR0U1UzBNM09GbzFWV1IzZHdwTWEwdHhLM05SVW1GcmExSk1Xa1ZDZDJoaloyaFFhRFJaTUZJclVFOXVRbkVyYTNremEwMUNOVmN3TkdWamJUQkRXRFJxUlV0bU4waEdhUzlJVlhsbUNuRldaSFY0YkcxdmVYZ3ljbW94YW5CVGEzWXZjR1ZxZEdaeWVGbFdhME4wVEVWc056ZDNiRmxVTmpkT1lVVTVWMDVYYjFKdmRrbGpUV053T1RFek5GSUtURm80WVhSMU9TOVdhbVZMU2twbmJWRXZTVzlhZUdWeWJpdE5RMnREYkV4RlNHdzJTbUZoVFZVMlVrWlFjRVJ6Y1ZWdUwyRm1ZazlWVEhoeE5YcDBOQW8wVW5Cc1RHSnZOR3BETW5scGJtWkRUa1JhVlRNd1UzaEViVzFDSzNkcGFtVTNkRms1TVZGTVYxSkVVRmRLVldRNFdtczlDaTB0TFMwdFJVNUVJRU5GVWxSSlJrbERRVlJGTFMwdExTMEsKICAgIHNlcnZlcjogImh0dHBzOi8vMTAuMjA3LjE0OS4yMDM6NjQ0MyIKICBuYW1lOiAibG9jYWwiCmNvbnRleHRzOgotIGNvbnRleHQ6CiAgICBjbHVzdGVyOiAibG9jYWwiCiAgICB1c2VyOiAia3ViZS1hZG1pbi1sb2NhbCIKICBuYW1lOiAibG9jYWwiCmN1cnJlbnQtY29udGV4dDogImxvY2FsIgp1c2VyczoKLSBuYW1lOiAia3ViZS1hZG1pbi1sb2NhbCIKICB1c2VyOgogICAgY2xpZW50LWNlcnRpZmljYXRlLWRhdGE6IExTMHRMUzFDUlVkSlRpQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENrMUpTVU0yVkVORFFXUkhaMEYzU1VKQlowbEpUV1JpU2tOdFlUTTNjMUYzUkZGWlNrdHZXa2xvZG1OT1FWRkZURUpSUVhkRmFrVlJUVUUwUjBFeFZVVUtRWGhOU0dFelZtbGFVekZxV1ZSQlpVWjNNSGxOVkVFMVRXcFplRTVxVVRKTlZFSmhSbmN3ZWsxVVFUVk5hbEY0VG1wUk1rMVVTbUZOUXpSNFJucEJWZ3BDWjA1V1FrRnZWRVJ1VGpWak0xSnNZbFJ3ZEZsWVRqQmFXRXA2VFZKTmQwVlJXVVJXVVZGRVJYZHdjbVJYU214TVYwWnJZbGRzZFUxSlNVSkpha0ZPQ2tKbmEzRm9hMmxIT1hjd1FrRlJSVVpCUVU5RFFWRTRRVTFKU1VKRFowdERRVkZGUVhoSFNHZElaRW8xSzFSWlZGRTVhVEYwVDBkT2FHOHZRWE15VFRnS1RVdDRPVE01TjBwQ1FXb3JTMmx6WWtacFoyVTJRamx3VW1obGJEQnBWRE42V21wTFVHZHFkSFZ4VjBWRlJGWkJVVXh2YmxaWEwxTjNPREF4V1ZsclR3cDZTVTkzZW5KUk5GazFiVmgyZWtwSFVGVnFSbkZUU25jdksxSnBXRWxhU0dsUFlXOVFWa0ZKY3pnM1FWSlNTMlUyYjJOMlJIaG9PVmh0SzFwaGMyODRDbXBJYjFFNVRYRkVUbmMwYTBSWWNHOUJUMlJMTm5Vdk5tMUlTRWRTUVZBME1IaFJVMmt5VlRJMmIyTXdVRVl6VUVaU2RIRldPRGxKVkhGcVoyZzVXWGtLVTBORUwxQlBMemxtVTNsUFpGRjBLeXRuV2toTllXb3JZMEZtT1UxTVZVdGtiVkZJUVV0ck1EbGhUREp1VkRKeGVIZ3dVekpETW1sVlZURTFjMVp2T1FwTWMxcG1hbEZ5YTFCeE9ERkNXRmhrVEVzd2JteHllWEZFVGpWeWRWcFlTelJMUldKdFJXeElNblY0YjBkVGRFVTVhVVpNY0VSdlQzaDNTVVJCVVVGQ0NtOTVZM2RLVkVGUFFtZE9Wa2hST0VKQlpqaEZRa0ZOUTBKaFFYZEZkMWxFVmxJd2JFSkJkM2REWjFsSlMzZFpRa0pSVlVoQmQwbDNSRkZaU2t0dldra0thSFpqVGtGUlJVeENVVUZFWjJkRlFrRkVhMUIxYjA5MlVHVmpaV2g1ZFZsU1MxbzBaaXQzV0VNNGNWQjNTbTFqU1hrclQyUmFWMko1U2s4NU5rWldNUXB5Uml0elpsVlhRU3RoTVRRMWFYQjJZMGd4UW1Wek1UUXpablk1V2pncmQyZG9lblJqSzBwYWJrRnNZWEphY2pKUlNDczRNMmw1VkhaeWVGSTNUa2xOQ20xMFdqVmlUbU5uZUhOM1EyVjBOVTV4WlN0S2JEWXlSM0I0YldSNVZVNDFSMmxWZDFSUlpFcHdURVIyVjNOd1ltVkVLMHRHYkhkVFMydGlNWHBUY0hBS1F6Z3ljV0ZqYlhoYVV5OUVjMjFCT0hSMWVXNXVlVWxEWVZWUlZYbHVSekowVlZJNWNUTTFhV1oyTVROdmMyaDNOazlzWkhwNk5qWXJRbTVIVUhWVlF3cFNSREZSTUU5QlduQnlTVGhyVUdscFlXZGthMjB5UldKb1IyVTBSbXhETUZkNWNuWkpPQ3M0U21rNWRFWktTaTlpYTJabE5YZE5hbE5GVlZsbFMwaG9Damx3ZVRKaGNFNWlkbkI1VXl0ek1uaFpUWGhoVTFwNGVFSldhMnhvTVhoM1VuQTBXbVEzY3owS0xTMHRMUzFGVGtRZ1EwVlNWRWxHU1VOQlZFVXRMUzB0TFFvPQogICAgY2xpZW50LWtleS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJTVTBFZ1VGSkpWa0ZVUlNCTFJWa3RMUzB0TFFwTlNVbEZiM2RKUWtGQlMwTkJVVVZCZUVkSVowaGtTalVyVkZsVVVUbHBNWFJQUjA1b2J5OUJjekpOT0UxTGVEa3pPVGRLUWtGcUswdHBjMkpHYVdkbENqWkNPWEJTYUdWc01HbFVNM3BhYWt0UVoycDBkWEZYUlVWRVZrRlJURzl1VmxjdlUzYzRNREZaV1d0UGVrbFBkM3B5VVRSWk5XMVlkbnBLUjFCVmFrWUtjVk5LZHk4clVtbFlTVnBJYVU5aGIxQldRVWx6T0RkQlVsSkxaVFp2WTNaRWVHZzVXRzByV21GemJ6aHFTRzlST1UxeFJFNTNOR3RFV0hCdlFVOWtTd28yZFM4MmJVaElSMUpCVURRd2VGRlRhVEpWTWpadll6QlFSak5RUmxKMGNWWTRPVWxVY1dwbmFEbFplVk5EUkM5UVR5ODVabE41VDJSUmRDc3JaMXBJQ2sxaGFpdGpRV1k1VFV4VlMyUnRVVWhCUzJzd09XRk1NbTVVTW5GNGVEQlRNa015YVZWVk1UVnpWbTg1VEhOYVptcFJjbXRRY1RneFFsaFlaRXhMTUc0S2JISjVjVVJPTlhKMVdsaExORXRGWW0xRmJFZ3lkWGh2UjFOMFJUbHBSa3h3Ukc5UGVIZEpSRUZSUVVKQmIwbENRVUZKWlZkREsyRk1TM2wxYXpacFp3cDBkREJpY21NMGN6Qk9VbVZzY2tOcWRUZDJiR2xHSzJSNFZHZHdVRTlMVWxScWQwMHdja3h3TkVkVlV6bDNWbXg0TlVSQ2QyVmlTV3RHVFc5aUsyZERDakpvWmtjelFYY3ljelJQTkRKamMwWkNTM2hIVEROSFRHNDJTakZhVjB0V00xZFJSWFJvYkdOdGJEaE1Tamg0YmxOS2RGbDFTemxRTlVzd1lVWldURTBLV1VseFYwcG5kMVozYURkMmVscFdjVmczU2pCWFRsRkpUMEZXV2t4ME1YTkhiRWxrUzJJMU5rTTBNRkZHYlc5MU9UZEpNVXhwVHpCMFlqZ3hPRzk2Y2dwWWNGaFNNMDlZVVVrMGQweFROMVFyVUhBclNVZGtVV1U0VkdaamExaFFlbEI1TWxrekwzSjFaMFpZTW5FclRWQndaWFozZVVjdmQwTldNbGhQVmk5VkNraFBZMWt6UzJwWlVrVklNR3hLVjNaQlF6UkJXbFp1YVVVck1GaHVWREZsUkd4clJuTlJVa0pCUVVwNU1UWm1VRmQ1WkhwTU0yeDFOMDU2UkVGbVlVNEtkVzlIY21keFJVTm5XVVZCTTBwRWJreGFSR3h6YWpaVFIxUm1jR2Q2UzJaUFVtdEZPREpHWVhaeFNsRkxibW9yZWtsUlVXRkxVbEl6VjBoM0wwNDRXUXBGT1VOalYxVlZjRkF6WlhSRFJuVm5XRFZHU0hCYU5USmlWRGgyUTBKVE0yeEJRVlZ5VEhWaU1UZDVZa1V4WW5ka1VrSm1NbkJOTjFvM1IxTTRVRTFOQ2xRdksxY3JaMHMzZDJGdVRVSjFZbTFGVkhGdGJHdFJZMjVaWlVaRmNFZGtlbGswY2pReE9ISkNRVTFpZVVoMmEwcHZkWHBHTVVWRFoxbEZRVFFyTldnS0sxSkNZMHR6YjNrNGIyVXhVWHBMWVdwUWRFdDRhM0o1ZFZCeVdIaDNObEE0VVhCRFlXNWliM3BxWkZaTU5FMW1aMmxMVUZGaFdYTkhha2g2U3pOd1RRcEtiRTA0VGtaRk1teElkRFpsWm1kalZqWklVbXh6TDBSVVMweGtiMEoySzBGUGMwUkhTbWgzYVdsSk9HRTJVRTFPZDFWWk5YUXZVemR0YVVGNlRqRnFDbEZNU2tGRlQyaEJlbWRvTm1Ga2R6VnZZMFJhVjB0M2FHMWpiMUphV0ZwbFJYUnFTemR3WTBObldVVkJjekl3U2sxeE9GcDJRWFJqYWtSc1NYTTFjVGtLYm1oUk1WTTRkVnB3TVZOb1FrUjNWR2R6YlRSRk0yZEJlRXRuUmtFMlFqQnNUVWg1VUd0cFpIbHRlVkJxVTI5RldqRnViWFk1YzA1dFkyUTFaV2RvYndwWmJsSkRXRlpZY3pZck5GazVVREpZWkVwUFUyUnNkWEJUY1hoUmVtTlFXamd3V1VoVGJrSnZlbkF4VkZKU1dWZGxSazlQTm5SVFZIUnhOV3N5V0hOMENuUlBZaTh5ZFVsNlQzWjBVVmxoU1haTmFFRlpOakZGUTJkWlFYWnlZbFJ0TUdGd1JqbFRaakZJWW1kdlFqRlVWeXQwV0c5YWRFMW9TMHNyYzFoMmNIb0tUa2M0ZVUxQkswRXlOR2hDVDFFclJsQkZPVEZNZUhBMGJrVjNLMjkzVmpneWRIQXdTWGw2YTI5SVR6bFJZelZFT0c5RFUwdEpSekEzVkdsdkwyeEpRd3A0VTFwUWNHTjFZM2xaTmxWQldqVTVVRGsyTW5CTmJFNTJObEkxZEdwSVJqTmpUMVJDWkVwUmFIVjBPR0V5Yms4d1ZGWnNNMEpRYmxKTFMyYzRPRXN6Q2psSmRESnVkMHRDWjBSR1VYUnJVWFJtVVdwcVlsUjBNQ3RCUXpKNmNsYzRMMjlPUWxkSFkxaHBTMWxIYjI0dlNEVnNiR3hEYVVsSlNGSnhPR3AyYmtFS1JISTBTR1ZaVW1KTllubFJXSFVyTkhwT2RUazJaR1JyVEdZdk1VVkxaV3hEYUZreVRYaG5hR2gxWjNWYWMwVldXbFpoU0hvelUxTjZhWEV5TkZSclpnbzJLMmRGY1dkUWJ6WkNRalo2YkU5T1lrUnBWbnBPVldsVFJGVjNZV2d5VkRCdk5rUnpaREoxY0hkT2JERTFOalpMTm5CUUNpMHRMUzB0UlU1RUlGSlRRU0JRVWtsV1FWUkZJRXRGV1MwdExTMHRDZz09
            - name: MIDDLE_PROXY_SERVER
              value: http://vbs-api-gateway-external-svc:8337
            - name: VBS_WEBAPP_LINK
              value: 'http://noo-dev.com'
            - name: EMAIL_SMTP_USER
              value: vbs_support@viettel1.com.vn
            - name: EMAIL_SMTP_PASS
              value: 'GPp53K!EnM6&'
            - name: REDIS_CLUSTER_SERVER
              value: '10.128.0.11:6379,10.128.0.11:6380,10.128.0.11:6381,10.128.0.10:6379,10.128.0.10:6380,10.128.0.10:6381,10.128.0.12:6379,10.128.0.12:6380,10.128.0.12:6381'
            - name: REDIS_CLUSTER_PASS
              value: 'ResdiiQTHT2022'
            - name: PUBLIC_APP_GATEWAY_URL
              value: 'https://app.noo-dev.com/noodev'
            - name: MAX_CPU_CAPACITY
              value: '5000'
            - name: MAX_MEMORY_CAPACITY
              value: '10240'
        ports:
          - containerPort: 8000
            protocol: TCP
          - containerPort: 8001
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /common/health/check
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 3
          failureThreshold: 100
        resources:
          requests:
            cpu: "500m"
            memory: "1024Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
